### ISSUE TITLE
[request]have it work with the tier 2 miner as well

### ISSUE THREAD

**Issue by Layarion** [enriquein/MinerVeinCoverage#2]
There's an advanced miner, and this mod doesn't seem to work with it.

**Comment by enriquein** [comment]
That's not a bad idea. I think I was going to add it at some point but then stopped playing once they announced the next big content update. This isn't a promise, but I'll see if I can take a few minutes in the upcoming weeks to see how viable this change would be. I have been in the mood to go back to DSP anyway, so this is as good of an excuse as any 😅

**Comment by Layarion** [comment]
well thanks for reading it.

ya what i want it to do, is show me what it can get per minute at the power level it's set to. It can scale between %100 to %300 but it doesn't bother telling you what that means unless it happens to be empty when you set it.

**Comment by enriquein** [comment]
I just uploaded a new version (1.4) with experimental support for the Advanced Miner. Please try it out and let me know if it works for you.

**Comment by Layarion** [comment]
ok i tried it out and it gets the basic job done. 

I noticed that it only works in increments of 100's. So it only updates the UI at 100%, 200%, and 300%. It doesn't show me what i'm getting at say, 125 or 150% percent, instead it shows me what i get at 100% until i hit the 200% marker.

Updating every 25% or 50% instead of the current every 100% would be better, but even as is i'd say it's a great update.

**Comment by enriquein** [comment]
Thanks for catching that. That was an unintentional bug related to number rounding issues. I uploaded version 1.4.1 to address this. It may take a few minutes for it to show up in the store/mod manager.

**Comment by Layarion** [comment]
seems to be working fine! ty
