### ISSUE TITLE
[minor][suggestion]grammar/presentation is a tad off

### ISSUE THREAD

**Issue by Layarion** [enriquein/MinerVeinCoverage#3]
![image](https://user-images.githubusercontent.com/7917992/233803719-38dd2f1d-c688-42f6-9364-17afbf9d5946.png)

1) I feel like you should just get rid of all the parentheses. We don't usually write out "hey do you want some apple(s)?"
1.1) also the number will probably still be easy to spot without the parentheses around it. take that with a grain of salt though, i'm just the kind of person that doesn't like extra visual clutter in my UI.

2) should probably change "Cover" to "Covers". I get that if it's only covering 1 vein, that "covers" would seem odd, but I imagine it's very rare that only 1 vein gets covered.

3) the space between "297" and the slash, should be removed if that was added there. Same for the space between the slash and the "min"

**Comment by enriquein** [comment]
I agree with you with the space around the `/`. I will probably remove it in a future release. I can't even remember why I put it there in the first place, as I'm not a huge fan of unnecessary padding between things.

The "Cover X vein(s)" text however is actually the game's English translation for that text label. The only way (I know of) to change that would be to force it to the English version without the `(s)`. That would mean non-English speakers would lose their localized version of the text, and that's not something I want to do. I wonder if there's a way for me to override the default translations, but I guess that's a topic for another day.

**Comment by Layarion** [comment]
it is what it is then. are you able to get rid of some of the parentheses without doing all that translation mucking about?

also, i just discovered that github updates webpages live, as i seen your response just pop in on the bottom as i was looking over my post for errors lol.

**Comment by enriquein** [comment]
> it is what it is then. are you able to get rid of some of the parentheses without doing all that translation mucking about?

Most I can do is change the text if the game is already in English to replace the `(s)` with an `s`. However, I don't think I'll remove the parens enclosing the max amount per min/sec. 

> also, i just discovered that github updates webpages live, as i seen your response just pop in on the bottom as i was looking over my post for errors lol.

Same here!

**Comment by enriquein** [comment]
I just published version 1.4.2 including the space and the parens tweaks. Also now conditionally hide the "Cover" word from the Advanced Mining Machine if ore is stacking (to prevent the overlap).

**Comment by Layarion** [comment]
all of said changes are working as intended!
